### ISSUE TITLE
Exception in pointcloud_link

### ISSUE THREAD

**Issue by zacwitte** [WPI-ARC/datalink_toolkit#10]
I've tried all the compression types for the pointcloud link and all of them have an exception after the first message trying to free memory. In addition, the PCL and PC60 seem to have other, unrelated warnings. This is all compiled in my catkin workspace on ROS Indigo with Ubuntu 14.04. Here are a couple examples:

teleop_compression_node.launch
```
<?xml version="1.0"?>

<launch>
	<node pkg="opportunistic_link" type="request_pointcloud_link_startpoint" name="velodyne_pointcloud_link_startpoint" output="screen" >
		<param name="pointcloud_topic"  type="string"   value="/velodyne_points" />
		<param name="compression_type"  type="string"   value="PC60" />
		<param name="data_service"      type="string"   value="/velodyne_points_data" />
		<param name="link_topic"        type="string"   value="/velodyn_points_compressed" />
	</node>
</launch>
```

teleop_decompression_node.launch
```
<?xml version="1.0"?>

<launch>
	<node pkg="opportunistic_link" type="request_pointcloud_link_endpoint" name="velodyne_pointcloud_link_endpoint" output="screen" >
		<param name="relay_topic"          type="string"   value="/velodyne_points_uncompressed" />
		<param name="data_service"         type="string"   value="/velodyne_points_data" />
		<param name="rate_ctrl"            type="string"   value="/velodyne_points_rate" />
		<param name="link_topic"           type="string"   value="/velodyn_points_compressed" />
		<param name="latched"              type="bool"     value="true" />
		<param name="default_rate"         type="double"   value="5" />
		<param name="default_filter_size"  type="double"   value="0.1" />
		<param name="filter_ctrl"          type="string"   value="/velodyne_points_quality" />
		<param name="override_timestamps"  type="bool"     value="false" />
		
		<!-- <remap from="/tf" to="/tf" /> -->
	</node>
</launch>
```

ZLIB:
```
process[velodyne_pointcloud_link_startpoint-1]: started with pid [19478]
[ INFO] [1461618865.737210108]: Starting request pointcloud link startpoint...
[ INFO] [1461618865.756955066]: Relay using ZLIB compression
[ INFO] [1461618865.756989238]: ...startup complete
[ INFO] [1461618874.008745110]: Compression of 22.731546 % took 0.004967 seconds
[ INFO] [1461618874.008783688]: Original size: 440.256000 KB - Compressed size: 100.077000 KB
[ INFO] [1461618874.008890676]: Responded with a single message
[ WARN] [1461618874.019460789]: Single message requested, none available
*** Error in `/home/zac/mBot/ros/devel/lib/opportunistic_link/request_pointcloud_link_startpoint': double free or corruption (out): 0x00007ffcea4a4900 ***
```

PCL:
```
process[velodyne_pointcloud_link_startpoint-1]: started with pid [21847]
[ INFO] [1461619036.722727318]: Starting request pointcloud link startpoint...
[ INFO] [1461619036.735261220]: Relay using PCL compression
[ INFO] [1461619036.735347653]: ...startup complete
Failed to find match for field 'rgb'.
[ INFO] [1461619048.874611953]: Compression of 11.657387 % took 0.012872 seconds
[ INFO] [1461619048.874654928]: Original size: 589.120000 KB - Compressed size: 68.676000 KB
[ INFO] [1461619048.874674814]: Responded with a single message
*** Error in `/home/zac/mBot/ros/devel/lib/opportunistic_link/request_pointcloud_link_startpoint': free(): invalid size: 0x00007ffe047225f0 ***
```

PC60:
```
process[velodyne_pointcloud_link_startpoint-1]: started with pid [22588]
[ INFO] [1461619086.745956287]: Starting request pointcloud link startpoint...
[ INFO] [1461619086.761933569]: Relay using PC60 compression
[ INFO] [1461619086.761975220]: ...startup complete
PFRAME_COUNTER_: 0 IFRAME_RATE_: 5
[ INFO] [1461619092.588073608]: Start IFRAME encode
[ INFO] [1461619092.590120927]: Compression of 10.495540 % took 0.005677 seconds
[ INFO] [1461619092.590149204]: Original size: 463.616000 KB - Compressed size: 48.659000 KB
[ INFO] [1461619092.590162542]: Responded with a single message
[ WARN] [1461619092.600189151]: Single message requested, none available
*** Error in `/home/zac/mBot/ros/devel/lib/opportunistic_link/request_pointcloud_link_startpoint': free(): invalid size: 0x00007ffeb15181d0 ***
```

**Comment by calderpg** [comment]
Hi, can you run the compression node under GDB and include a backtrace from the error?

**Comment by zacwitte** [comment]
```
zac@zac-nuc-2:~/mBot/ros/devel/lib/opportunistic_link$ gdb request_pointcloud_link_startpoint
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from request_pointcloud_link_startpoint...(no debugging symbols found)...done.
(gdb) run _link_topic:=/velodyne_points_compressed _data_service:=/velodyne_points_data _pointcloud_topic:=/velodyne_points _compression_type:=PC60
Starting program: /home/zac/Dropbox/Projects/Code.Zac/mBot/ros/devel/lib/opportunistic_link/request_pointcloud_link_startpoint _link_topic:=/velodyne_points_compressed _data_service:=/velodyne_points_data _pointcloud_topic:=/velodyne_points _compression_type:=PC60
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[ INFO] [1461621531.289795357]: Starting request pointcloud link startpoint...
[New Thread 0x7fffdf10c700 (LWP 11254)]
[New Thread 0x7fffde90b700 (LWP 11255)]
[New Thread 0x7fffde10a700 (LWP 11256)]
[New Thread 0x7fffdd909700 (LWP 11261)]
[ INFO] [1461621531.311453150]: Relay using PC60 compression
[ INFO] [1461621531.311551712]: ...startup complete
PFRAME_COUNTER_: 0 IFRAME_RATE_: 5
[ INFO] [1461621552.754786718]: Start IFRAME encode
[ INFO] [1461621552.757162958]: Compression of 10.218656 % took 0.007142 seconds
[ INFO] [1461621552.757191647]: Original size: 589.696000 KB - Compressed size: 60.259000 KB
[ INFO] [1461621552.757212216]: Responded with a single message
[ WARN] [1461621552.765795601]: Single message requested, none available
*** Error in `/home/zac/Dropbox/Projects/Code.Zac/mBot/ros/devel/lib/opportunistic_link/request_pointcloud_link_startpoint': double free or corruption (out): 0x00007fffffffc6f0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff52a9cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff52a9cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff52ad0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff52e6394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff53f4b28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff52f266e in malloc_printerr (ptr=<optimized out>, str=0x7ffff53f4c58 "double free or corruption (out)", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff7bc4c8b in boost::detail::sp_counted_impl_p<pcl::PCLPointCloud2>::dispose() ()
   from /home/zac/mBot/ros/devel/lib/libpointcloud_compression.so
#6  0x00007ffff793c4ee in boost::detail::sp_counted_base::release() () from /usr/lib/libpcl_common.so.1.7
#7  0x00007ffff793b2ba in pcl::PCLBase<pcl::PCLPointCloud2>::setInputCloud(boost::shared_ptr<pcl::PCLPointCloud2 const> const&) ()
   from /usr/lib/libpcl_common.so.1.7
#8  0x00007ffff7bc4404 in pointcloud_compression::PointCloudHandler::compress_pointcloud2(sensor_msgs::PointCloud2_<std::allocator<void> >&, unsigned char, float) () from /home/zac/mBot/ros/devel/lib/libpointcloud_compression.so
#9  0x0000000000414337 in RequestPointcloud2LinkStartpoint::data_cb(datalink_msgs::RequestPointCloud2Request_<std::allocator<void> >&, datalink_msgs::RequestPointCloud2Response_<std::allocator<void> >&) ()
#10 0x00000000004181cc in ros::ServiceCallbackHelperT<ros::ServiceSpec<datalink_msgs::RequestPointCloud2Request_<std::allocator<void> >, datalink_msgs::RequestPointCloud2Response_<std::allocator<void> > > >::call(ros::ServiceCallbackHelperCallParams&) ()
#11 0x00007ffff66389a9 in ros::ServiceCallback::call() () from /opt/ros/indigo/lib/libroscpp.so
#12 0x00007ffff667a137 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/indigo/lib/libroscpp.so
#13 0x00007ffff667af33 in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/indigo/lib/libroscpp.so
#14 0x00007ffff66aa645 in ros::spinOnce() () from /opt/ros/indigo/lib/libroscpp.so
#15 0x000000000040f34d in main ()
(gdb) 
```

**Comment by calderpg** [comment]
This should now be fixed. The pointcloud2 pointer used by the voxel filter was being double-free'd accidentally. Please test and let me know if the problem continues.

**Comment by zacwitte** [comment]
It works! Thanks for the quick fix.
